barrett:
  apiToken: "![GBE7kujDfrOeaOBjGcAm6QysrCS+Lg+JqJtvEBE4HLO29h7p0gwAI6GlX2Qyvkx7M/a8R5CpDysbokezaA+ttrgr2CZQZ2x+8CwYr8O9SCs=]"

tigers:
  salesOrder:
    apiToken: "![Fq2crybCFD5FzJAPDzBAjgnEXWPduHxD2K07hYCr7P5vZjxmmAAQclCP0uxhu+2VHpCQ7mE19xaEPTRPxro2V7jBfOFO7uYLSlFNrQFZT9pK/yYiGpIS/I/ZTKydvzDAceSbTG9khev+alziynfyKikThbHbUyWNmITt9vqvRF23xaJFh3hmfry2bY3TTmpsTuIl1O6ctFg4AKcyJ61dNxDqT3y+capx0Id5QbzhNAZtEY9Zo0SHXtz0d7hV3SPOFv/5/HwjIwGZLSSMjXR3xBCBTw0lbDLHvzC5NyaeQXMQEjXcHIrHLKPO5P1ReQjNm+XS6Fwk6SERxAkkVedHdj4S9Xm6M0IgYtLgtgRBW1Q0WB4jAIf3BGlF7J9ivIg4v8UlPBSdK2Shv75X8VwcKuN4qSymSJCaZcIEylvMnZ3uPlAlGlBLbWorumg2BGqvFoQnQijBqHwXx4POGpP9/Zk1hMhEGz8B6/AR3S/c12GfinYDSRsma7z9sApfsfyBuczKJT0qHwbeZbpw74MykbFLaBRMGiGa5EClqcndp2R2v6PZ8AA6tkex8QFZffp5]"
  
https:
  keyPass: "![93NDkOSkI1Y57tNDWLY9lw==]"